services:
  app:
    user: "1000:1000"
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www

  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www
    depends_on:
      - db
      - app

  composer:
    user: "1000:1000"
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: